{
    "id": "unhandled-assertion-error",
    "title": "AssertionError Example",
    "version": "1.0.0",
    "description": "Demonstrate an AssertionError (assert statement fails).",
    "instructions": "Run the code. You should see:\n```\nTraceback (most recent call last):\n  File \"assertion_error.py\", line 1, in <module>\n    assert 2 + 2 == 5, \"Math is broken!\"\nAssertionError: Math is broken!\n```",
    "feedback": "",
    "tests": "",
    "starter": "assert 2 + 2 == 5, 'Math is broken!'\n",
    "files": {"/assertion_error.py": "assert 2 + 2 == 5, 'Math is broken!'\n"},
    "fileReadOnlyStatus": {}
}
